
name: Generate and Update Profile Data

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Update Profile and Contribution Data
    runs-on: ubuntu-latest
    
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      # Install Dependencies
      - name: Install Dependencies
        run: pip install -r requirements.txt  # Assuming you have a requirements.txt file

      # Generate GitHub Contribution Snake Animation
      - uses: Platane/snk@v1.0.0
        id: snake-gif
        with:
          github_user_name: ericafnunes
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Update README.md with the latest stats
      - name: Update README with Latest Stats
        run: python update_readme.py

      # Run Linters (Example)
      - name: Run Linters
        run: flake8  # Assuming you're using flake8 as a linter
      
      # Run Automated Tests (Example)
      - name: Run Tests
        run: pytest  # Assuming you're using pytest for testing

      # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update README and Contribution Snake"
          git push

      # Publish to GitHub Pages and Push README changes
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
